name: Sync Fork with Upstream

on:
  schedule:
    - cron: "0 0 * * *"  # Run daily at midnight UTC
  workflow_dispatch:  # Allow manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout fork
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/Havesta-Logistics-Limited/havesta_marketplace_v1.git
          git fetch upstream

      - name: Check for upstream changes
        id: check_changes
        run: |
          git checkout main
          BEHIND=$(git rev-list --count HEAD..upstream/main)
          echo "behind=$BEHIND" >> $GITHUB_OUTPUT
          if [ "$BEHIND" -gt 0 ]; then
            echo "Fork is $BEHIND commits behind upstream"
            echo "has_changes=true" >> $GITHUB_OUTPUT
          else
            echo "Fork is up to date with upstream"
            echo "has_changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Merge upstream changes
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          git merge upstream/main --no-edit

      - name: Push changes to fork
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          git push origin main

      - name: Create summary
        run: |
          if [ "${{ steps.check_changes.outputs.has_changes }}" == "true" ]; then
            echo "✅ Successfully synced fork with upstream changes" >> $GITHUB_STEP_SUMMARY
          else
            echo "ℹ️ Fork is already up to date with upstream" >> $GITHUB_STEP_SUMMARY
          fi
